# Generated by Django 3.1 on 2021-11-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_batch_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchintegrity',
            name='offline_wallet_sent',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AlterField(
            model_name='batch',
            name='anfp',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
