# Generated by Django 3.1 on 2022-01-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_auto_20211125_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchintegrity',
            name='batch_lot_raddress',
            field=models.CharField(max_length=34, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batchintegrity',
            name='integrity_address',
            field=models.CharField(max_length=34, null=True, unique=True),
        ),
    ]
