# Generated by Django 3.1 on 2022-04-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_auto_20220112_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='anfp',
            field=models.CharField(max_length=8),
        ),
    ]
