# Generated by Django 3.1 on 2022-08-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0101_remove_post_is_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='anfp',
            field=models.CharField(max_length=20),
        ),
    ]
