# Generated by Django 3.1 on 2022-09-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0102_auto_20220831_2039'),
        ('batch', '0102_auto_20220831_1346'),
    ]

    operations = [
    ]
